FROM  hub.c.163.com/library/java:8
VOLUME /tmp
ADD JAVA_Account-Service-0.0.1-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 9000
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]